# Generated by Django 2.1.5 on 2020-05-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
