# Generated by Django 2.1.5 on 2020-05-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200529_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
